{% set name = "fontparts" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fontParts-{{ version }}.zip
  sha256: 2f0121bcbab1dd5bb5a2673f42b182a6d403db94dbbfd3a4e5e4d444bde1bc44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm ==7.0.5
  run:
    - booleanoperations >=0.9.0
    - defcon >=0.6.0
    - fontmath >=0.4.8
    - fonttools >=3.32.0
    - python >=3.7

test:
  imports:
    - fontParts
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/robotools/fontParts
  summary: An API for interacting with the parts of fonts during the font development process.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
