{% set name = "fontparts" %}
{% set version = "0.12.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: f0921c33f93b02ff8024fed78d65c78da09a610029c6c40c02ff62179459fd8e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm ==7.0.5
    - setuptools
  run:
    - booleanoperations >=0.9.0
    - defcon >=0.6.0
    - fontmath >=0.4.8
    - fonttools >=3.32.0
    - python >={{ python_min }}

test:
  imports:
    - fontParts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/robotools/fontParts
  summary: An API for interacting with the parts of fonts during the font development process.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
